### ISSUE TITLE
kodi.log path error in windows platform

### ISSUE THREAD

**Issue by kolekan** [henryjfry/repository.thenewdiamond#15]
I'm getting error in line 903 of resources/lib/process.py file  (v.7.42) about kodi.log path in windows 10 kodi 20.

`logfn = xbmcvfs.translatePath(r'special://home/temp\kodi.log')` is correct for android but not for windows.
for all platforms must be `logfn = os.path.join(xbmcvfs.translatePath('special://logpath'), 'kodi.log')`

**Comment by henryjfry** [comment]
Ahh ok, i think that's just for something I added to try and capture YouTube playback failure.
So until I fix it if you disable the setting for the window stack to reopen if playback doesn't start it will not throw that error.

And I'll push an update later

**Comment by henryjfry** [comment]
Ok so i've fixed that particular error. Still trying to fine tune the reopening routine.
So when you click to play from the app it wants to reopen if playback fails, but determining playback failure is harder than it really should be.  Apps like seren dont keep the busy dialog open the whole time so you cant just have it triggering if the home screen is visible. And they go through a couple of "playback" steps as opening an addon counts as playback according to kodi.

So this may give some false positive triggers to pop the stack until I can get it tuned.
