### ISSUE TITLE
Trakt not working 

### ISSUE THREAD

**Issue by Tiagomartires1983** [henryjfry/repository.thenewdiamond#17]
Using Libreelec 10.95.1 , kernel 6.1.11  , Windows system X11  , Kodi 20.0-Nexus
Diamond Info_Mod 7.54
The MovieBd Helper 5.1.2

Track is not working , I try delete addon data from this 2 addons and reconnect Trakt but no joy .
i try install other versions of Moviedb and  Diamond but no joy.

Trak is connected on Moviedb Helper but the addon Diamond Info for some reason is not working and downloading the information .

Sending kodi log  , if ytou can help me  will be appreciated.  
  
[kodi.log](https://github.com/henryjfry/repository.thenewdiamond/files/10870964/kodi.log)

**Comment by henryjfry** [comment]
It looks for "<setting id="trakt_token">" and also "</setting>"

**Comment by Tiagomartires1983** [comment]
ok , So what i can  do fix this?

**Comment by henryjfry** [comment]
Ok not sure why that wouldnt work as it looks ok, unless there is a new line character or something messing things up.

If you wanted to try something you could change this:

`
    import html
    f = open(tmdb_settings, 'r')
    for x in f:
        if 'trakt_token' in x:
            trakt_token = x.split('</setting>')[0].split('<setting id="trakt_token">')[1]
            trakt_token = eval(html.unescape(trakt_token))
    f.close()
    del html
`

For this:

`
    import html
    trakt_token = xbmcaddon.Addon('plugin.video.themoviedb.helper').getSetting('trakt_token')
    trakt_token = eval(html.unescape(trakt_token))
    del html
`

In "script.diamondinfo/resources/lib/library.py"

And let me know if it works.
Otherwise wait till I get home and can push an update.

**Comment by henryjfry** [comment]
Yeah I'll apply that change, should really have been setup like that before but i'm an "if it aint broke don't fix it" kind of coder.

**Comment by henryjfry** [comment]
closed with update
