### ISSUE TITLE
Error with version 7.77 of Extended Info-Diamond_MOD -addon still works fine

### ISSUE THREAD

**Issue by cg00001** [henryjfry/repository.thenewdiamond#21]
I don't know if this is a Linux issue:
![1](https://github.com/henryjfry/repository.thenewdiamond/assets/38960370/709c6d01-27df-43c9-9eee-874431489e80)
![2](https://github.com/henryjfry/repository.thenewdiamond/assets/38960370/83049477-a827-4622-9f81-9d4d92dc4807)

**Comment by henryjfry** [comment]
I'm sure it's an android issue, it's missing a module pkg_resources which is supposed to be built-in.

Thought I'd resolved that.

**Comment by henryjfry** [comment]
Can you confirm what OS you are getting that error on?
I got a bunch of dependency errors with the updates on android with the missing pkg_resources but I thought I had fixed the version i bundled into the addon enough that it should have worked.

I got a bunch of different dependency errors on windows for "importlib_resources" and "zipp" on Kodi 19.4 which i've now bundled modules for.

So i'd like to know if this is something i can test or not.

**Comment by cg00001** [comment]
Arch Linux.

**Comment by cg00001** [comment]
> I'm sure it's an android issue, it's missing a module pkg_resources which is supposed to be built-in.
> 
> I'd tested on android and thought it was all working, this may require your assistance to fix as ive tried it on android and don't get that error.
> 
> edit:
> 
> I realize that your screenshots above are on a linux system? However that shouldn't really have too much impact, im also on a linux based kodi setup (osmc) however i have installed stuff through python + setuptools so that would have installed pkg_resoucres if it wasnt already installed.
> 
> But v7.77 and definetly v7.78 have their own version of pkg_resources included and the directory they are in added to the pythohn PATH, so it shouldnt give that error. Im hoping you hadnt restarted and it hadnt put all the right paths into the python PATH yet?

Actually, since I didn't know what to do I uninstalled it completely -addon_data Extended Info folder too- and awaiting instructions.

**Comment by henryjfry** [comment]
Ok well can you reinstall 7.78 and let me know if you get the same error?

I might need you to do some terminal things potentially and/or trial and error debugging.
But i made a small change in 7.78 which i'm hoping is importing the relevant module correctly.

If not trying to resolve it could be tricky.

**Comment by cg00001** [comment]
It's probably because I used Kodi Omega -and forgot to mention.
The same second v7.80 install finished there was the same error:
![1](https://github.com/henryjfry/repository.thenewdiamond/assets/38960370/f1856a55-b530-4bbc-9c7f-a2e49f9a88b5)
![2](https://github.com/henryjfry/repository.thenewdiamond/assets/38960370/423a051f-6d70-4ab2-a85d-f530c4e3b0ac)

In Kodi Nexus there's no error at all, Extended Info v7.80 works fine.

**Comment by henryjfry** [comment]
Ahh i googled kodi Omega, I thought it might have been really old but its actually the very newest, is that alpha or actually a release version?
If its a release version then you should report the error as they would need to make sure to include that module.

But otherwise I can mark this as resolved?
Have you noticed any improvements?

**Comment by cg00001** [comment]
Omega Alpha 3 (latest) is faster than Nexus v20.2 in general, so Extended Info is faster too.
There's a personal issue with me and a Kodi Linux dev, since it is an alpha, the past 2 issues I opened about problematic dependencies, even lib problems that made Kodi not even start, he answered "It's fixed on git, rebuild from scratch". I'm using a prebuilt Arch package and have to alert the maintainer to built it so I can install Kodi in seconds instead of building it for more than 10 hours.
So I couldn't open an issue until Omega hits stable.

Yeah, addon works extra fine in Nexus, so this issue is closed.
