### ISSUE TITLE
Extendedinfo no longer Bingie Mod after upgrade from 2.03 to 2.20 Omega

### ISSUE THREAD

**Issue by minhgi** [henryjfry/repository.thenewdiamond#25]
I get this error clicking on "Extended Info" button.  Seem like it links to TheMovieDB Helper rather than Diamond ExtendedInfo.  You have any suggestions to fix it? I can do light editing to python script if I have to fix this issue.
![2024-05-11_174917](https://github.com/henryjfry/repository.thenewdiamond/assets/4175702/446c2e7d-26cd-435f-bb06-bf2faaecd690)

**Comment by henryjfry** [comment]
I believe the change you need to make is in the file here:

/xml/IncludesDialogVideoInfo.xml

````
							<!--Extended Info Button-->
							<label>31269</label>
							<width>285</width>
							<height>40</height>
							<align>center</align>
							<textoffsetx>0</textoffsetx>
                            <visible>Skin.HasSetting(videoinfo_button_extendedinfo)</visible>
                            <onclick condition="!System.HasAddon(script.extendedinfo)">RunPlugin(plugin://script.extendedinfo)</onclick>
							<onclick condition="System.HasAddon(script.extendedinfo) + $EXP[IsMovieDBType]">RunScript(script.extendedinfo,info=extendedinfo,dbid=$INFO[ListItem.DBID],name=$INFO[ListItem.Title])</onclick>
                            <onclick condition="System.HasAddon(script.extendedinfo) + $EXP[IsTvShowDBType]">RunScript(script.extendedinfo,info=extendedtvinfo,dbid=$INFO[ListItem.DBID],name=$INFO[ListItem.TvShowTitle])</onclick>
                            <onclick condition="System.HasAddon(script.extendedinfo) + [String.IsEqual(ListItem.DBTYPE,season) | String.IsEqual(ListItem.Property(DBTYPE),season)]">RunScript(script.extendedinfo,info=seasoninfo,tvshow=$INFO[ListItem.TvShowTitle],season=$INFO[ListItem.Season],silent=True)</onclick>
                            <onclick condition="System.HasAddon(script.extendedinfo) + $EXP[IsEpisodeDBTypeNoFallback]">RunScript(script.extendedinfo,info=extendedepisodeinfo,dbid=$INFO[ListItem.DBID],tvshow=$INFO[ListItem.TvShowTitle],season=$INFO[ListItem.Season],episode=$INFO[ListItem.Episode],silent=True)</onclick>
						</control>
                        <control type="button" id="112">
      
````

**Comment by minhgi** [comment]
Yeah.  When I choose to "Credit and More Info" replace with "Extended Info", the button link to TheMovieBD Helper rather the DiamodInfo.  Not sure what other options to switch unless Bingie Mode is coded to use TheMovieDB Helper rather than the  generic script.extendedinfo.

![image](https://github.com/henryjfry/repository.thenewdiamond/assets/4175702/5861110a-f4dd-4d87-b5ff-37a868c7a3e1)
![2024-06-09_180326](https://github.com/henryjfry/repository.thenewdiamond/assets/4175702/d619838a-e6ba-4aa5-b131-29690370e7b1)

**Comment by henryjfry** [comment]
Can you send me a link to the repo? The one i linked to isnt the same version I dont think

**Comment by minhgi** [comment]
This the link to the official Kodi Bingie Mod thread.
https://forum.kodi.tv/showthread.php?tid=355993

TBM repo:
https://achillespunks.github.io/repository.titan.bingie.mod/repository.titan.bingie.mod/

**Comment by henryjfry** [comment]
Ok so it appears that dispite what it might say on the label and in the settings that the extendedinfo functionality was removed in:

Update 2.1.0
https://github.com/AchillesPunks/skin.titan.bingie.mod/commit/2953f0c44358f3ee04ec3bff18cc6d4c0ed53ac8#diff-7ffa5adebc82192efdd4fa6c5bbc7af4e30cce9a8c1b7485565338b36e474436

If you find:

IncludesDialogVideoInfo.xml

And expand it with "load diff" and then search for "extendedinfo"

At line 1168 you'll see where all the actual "extendedinfo" stuff was removed:

````
								<onclick condition="!System.HasAddon(script.extendedinfo)">RunPlugin(plugin://script.extendedinfo)</onclick>
								<onclick condition="System.HasAddon(script.extendedinfo) + $EXP[IsMovieDBTypeNoFallback]">RunScript(script.extendedinfo,info=extendedinfo,dbid=$INFO[ListItem.DBID],name=$INFO[ListItem.Title])</onclick>
								<onclick condition="System.HasAddon(script.extendedinfo) + $EXP[IsTvShowDBTypeNoFallback]">RunScript(script.extendedinfo,info=extendedtvinfo,dbid=$INFO[ListItem.DBID],name=$INFO[ListItem.TvShowTitle])</onclick>
								<onclick condition="System.HasAddon(script.extendedinfo) + [String.IsEqual(ListItem.DBTYPE,season) | String.IsEqual(ListItem.Property(DBTYPE),season])">RunScript(script.extendedinfo,info=seasoninfo,tvshow=$INFO[ListItem.TvShowTitle],season=$INFO[ListItem.Season],silent=True)</onclick>
								<onclick condition="System.HasAddon(script.extendedinfo) + $EXP[IsEpisodeDBTypeNoFallback]">RunScript(script.extendedinfo,info=extendedepisodeinfo,dbid=$INFO[ListItem.DBID],tvshow=$INFO[ListItem.TvShowTitle],season=$INFO[ListItem.Season],episode=$INFO[ListItem.Episode],silent=True)</onclick>
````

So what I would do is just add a 2nd button with the same onclic conditions as above.

**Comment by minhgi** [comment]
Replace button id=52  with the up above condition it stall load TheMovieDB Helper. 

![image](https://github.com/henryjfry/repository.thenewdiamond/assets/4175702/13c829bf-bcb8-4599-b73d-b12c0640fd01)
![image](https://github.com/henryjfry/repository.thenewdiamond/assets/4175702/e5e2d918-1c1d-4c96-bbb3-069fa47e8c4d)
![image](https://github.com/henryjfry/repository.thenewdiamond/assets/4175702/fe4dad09-bcb0-4971-bb11-be4ee0eb6d66)

**Comment by henryjfry** [comment]
Yeah im not a skinner and i wont be able to help fix this as i just dont know enough about how skins work. So im going to close this as it isnt an issue with my addon.
