### ISSUE TITLE
Addon version problem

### ISSUE THREAD

**Issue by kolekan** [henryjfry/repository.thenewdiamond#3]
Please change the new updated version of EIM from 3.2 to 3.20
3.2 is lower than 3.19 version
See how versioning works in 1.1.2 paragraph of
https://kodi.wiki/view/Addon.xml

**Comment by henryjfry** [comment]
Noted, i've updated my auto increment script so itll be fixed next update going forward

**Comment by henryjfry** [comment]
Version updated + auto increment script updated
