### ISSUE TITLE
[Thank You] Big Thank you for making extended info possible for kodi 19

### ISSUE THREAD

**Issue by Goldenfreddy0703** [henryjfry/repository.thenewdiamond#4]
Hey, i just wanted to say thank you so much for making extended info possible for kodi 19. This helped out on the Auramod Skin and this reminds me of OpenMeta & OpenInfo. Again, huge thanks for making it possible and i love your repo and also thank you so much for fixing Artwork Beef too.

**Comment by henryjfry** [comment]
Cheers
