### ISSUE TITLE
Little things that drive me crazy lol

### ISSUE THREAD

**Issue by mrgsi** [henryjfry/repository.thenewdiamond#7]
Ever since OpenInfo I've noticed the word "Soften" stuck in the description of all videos. Is there any way to get rid of that or do you know where it comes from? I tried digging though the code but I get lost in that jungle.
Also, for some reason when I select the IMDB Trailers player in TMDBH it plays in background. I have to back out of the EIM to see it, It works fine with the other players. Sometimes YouTube fails so using IMDB for trailers for movies is handy.

**Comment by G-streamer** [comment]
Thanks for your reply. I'm actually using Aeon-Nox-Silve but I will dig around in the xml to see if I can find that code. 
Much appreciated and awesome work you do.
