### ISSUE TITLE
[Feature Request] Any chance to add CSFD as autocompletion provider?

### ISSUE THREAD

**Issue by horizon911** [henryjfry/repository.thenewdiamond#9]
Hi,
Thanks for the addon updates!
I wonder: Would there a possibility to have www.csfd.cz added as autocompletion provider?
I found some reference to csfd autocompletion here...
https://github.com/bartholomej/node-csfd-api/blob/master/tests/mocks/movie1.html.ts
...Not sure, if it's of any help.

Thanks!
Horizon

**Comment by henryjfry** [comment]
Ok so I had a look at the site and it doesn't appear to have an official API.
The link you provided appears to be a Java script app which can interact with the site? 
But I'm no good with Java script and the site is in polish so both those facts combined make it difficult to figure out where to begin.

If you can figure out how to trigger and return some of the functionality of node-csfd-api from within python then I could probably get it integrated.

But I poked around and couldn't figure it out myself.

**Comment by horizon911** [comment]
Heyyyy,
Thanks for looking into this! Hmmmm, it's all Greek to me.

If CSFD does not do the job, could TMDB or Trakt help? They do seem to offer APIs....

This is what I found:

  1.  TMDB: 1<https://python-tmdb3.readthedocs.io/_/downloads/en/latest/pdf/>, 2<https://www.themoviedb.org/talk/5522bb689251415c7f0060aa>, 3<https://stackoverflow.com/questions/57958733/how-do-i-put-an-autocomplete-based-on-api-request>
  2.  Trakt.Tv: https://trakt.docs.apiary.io/#
  3.

Regards
--Lukas
________________________________

**Comment by henryjfry** [comment]
Well they do have APIs but they don't have anything like autocomplete I don't think.
I updated the autocomplete parts in the repo as extendedinfo and skins connect to it. But I don't investigate the Google API call or the other provider(s) too much. However it's a continual search each time to type a new letter returning likely matches, getting results back from a non autocomplete API (tmdb for example) would provide no useful results, I think it only finds movies exactly matching what you type. Keywords are a little different but still wouldn't work for autocomplete.

I do think the autocomplete has language options and at least one other non Google provider. Amazon maybe? The only other one I can think that would likely work is IMDb, but they dont have any actual api either

**Comment by horizon911** [comment]
Ah, I see. It seems to be much more complicated than I thought it would originally be. 😄

Both (as well as multisearch) might IMO return something useful.

But my biggest problem is that it does not seem to handle diacritics right, e.g.:
https://www.themoviedb.org/search/multi?query=návště
AND
https://www.themoviedb.org/search/multi?query=navste
...should return the same results. But it does not, which breaks badly for me.

If I notice anything of the interest, I'll let you know. Thanks for everything! 🙂

Regards
--Lukas

________________________________
